#pragma config(Sensor, dgtl1,  camShaft,       sensorRotation)
#pragma config(Motor,  port2,           rightBackWheel, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftFrontWheel, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftBackWheel, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rightFrontWheel, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           pullBackR1,    tmotorVex393, openLoop)
#pragma config(Motor,  port7,           pullBackR2,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           pullBackL1,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           pullBackL2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int z = 0;
	while (true)
	{
		//Wheels

		//Right joystick controlls the robots movement forward and backward and turning
	  //Left joystick controlls the robots movement forward and backward and straifing
	  motor(rightFrontWheel) = vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch2] - vexRT[Ch1];
	  motor(leftFrontWheel) = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch2] + vexRT[Ch1];
	  motor(rightBackWheel) = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch2] - vexRT[Ch1];
	  motor(leftBackWheel) = vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch2] + vexRT[Ch1];


	  //crossbow
	  int x;

	  //Botton 6U sets the pullback speed to 85
	  if(vexRT(Btn6U)==1)
	  {
	  	x = 130;
	  	z = 0
		}

		//sets the motors equal to x
		motor(pullBackR1) = x;
	  motor(pullBackR2) = x;
	  motor(pullBackL1) = x;
	  motor(pullBackL2) = x;

	  //Botton 8D stops the pull back
	  if(vexRT(Btn8D)==1)
	  {
	  	x=0;
		}

		//Botton 6D sets the pullback speed to 65
		if(vexRT(Btn6D)==1)
	  {

	  x = 100;
		}

		//cam shaft encoder``
		int y = int;
		if(Btn6U = 0){
			if(z = 0){
				y = SensorValue(camShaft);
				z = 1;
			}
			if(SensorValue(camShaft) < y){
						x = 80;
			}
			if(SensorValue(camShaft) > y){
						x = -80;
			}
			if(SensorValue(camShaft) = y){
						x = 0;
			}
		}

	}
}
