#pragma config(Motor,  port7,           L1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           R2,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void gearSpeed(int s)
{
	motor(L1) = s;
	motor(R1) = s;
	motor(R2) = s;
}

task main()
{
	int x = 30;
	while(true) {
		gearSpeed(x);
		if(vexRT(Btn8U)==1){
			x += 10;
		}
		if(vexRT(Btn8D)==1){
			x += 10;
		}
		delay(10);
	}
}
